name: Build Cheat
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Build Solution
      run: msbuild Evelion.sln /p:Configuration=Release /p:Platform=x86
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Tayyor_Cheat
        path: Release/
